// FIFO Design Configuration File
// Generated by flow manager before logic synthesis
// Will be deleted if '/ubc/ece/home/gl/grads/ameer/fifo/cell-based_mixed_fifo.flow.aug16-3/scr/do cln' is applied

`define SNDTYP "asps"				// Sender   protocol type: asps/clkd
`define RCVTYP "asps"				// Receiver protocol type: asps/clkd
`define OPRFRQ 600				// Operation frequency in MHz
`define STAGES 8				// Number of FIFO stages
`define DATAWD 8				// FIFO data width
`define SYNCDP 2				// FIFO brute-force synchronizer depth
`define PIPESA 0				// Pipeline spaceav?
`define PIPEDV 0				// Pipeline datav  ?
`define RUNNAM "asps2asps_8X8_600MHz_2FF_0_0"	// Run name identifier

// Simulation related parameters
`define SIMPUTPERSCL 1		// Simulation put period scale
`define SIMGETPERSCL 1		// Simulation get period scale
`define SIMPUTDTYCYC 0.5	// Simulation put duty cycle
`define SIMGETDTYCYC 0.5	// Simulation get duty cycle
`define SIMDATALN    1000	// Simulation data length
